### ISSUE TITLE
Ошибка при работе скрипта на базе библиотеки

### ISSUE THREAD

**Issue by emelkas** [cia76/AlorPy#1]
Добрый день.
Для начала хотелось бы сказать спасибо за данную библиотеку, а так же QuikPy и BackTraderQuik. Я начинающий программист, но с комментариями к коду и примерами получается понять что к чему и писать на этой базе свои скрипты.

При тестировании скрипта на базе AlorPy столкнулся со следующей ошибкой. Как сказал ранее, я новичок и мне сложно емко сформулировать ошибку, поэтому привожу весь листинг. ошибка вылезла через 3 часа после работы скрипта.

Traceback (most recent call last):

  File "/Users/emels/YD/Python/Alor_pilot/venv/lib/python3.10/site-packages/urllib3/response.py", line 700, in _update_chunk_length
    self.chunk_left = int(line, 16)

ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/Users/emels/YD/Python/Alor_pilot/venv/lib/python3.10/site-packages/urllib3/response.py", line 441, in _error_catcher
    yield

  File "/Users/emels/YD/Python/Alor_pilot/venv/lib/python3.10/site-packages/urllib3/response.py", line 767, in read_chunked
    self._update_chunk_length()

  File "/Users/emels/YD/Python/Alor_pilot/venv/lib/python3.10/site-packages/urllib3/response.py", line 704, in _update_chunk_length
    raise InvalidChunkLength(self, line)
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/Users/emels/YD/Python/Alor_pilot/venv/lib/python3.10/site-packages/requests/models.py", line 760, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/Users/emels/YD/Python/Alor_pilot/venv/lib/python3.10/site-packages/urllib3/response.py", line 575, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/Users/emels/YD/Python/Alor_pilot/venv/lib/python3.10/site-packages/urllib3/response.py", line 755, in read_chunked
    with self._error_catcher():

  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)

  File "/Users/emels/YD/Python/Alor_pilot/venv/lib/python3.10/site-packages/urllib3/response.py", line 458, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/Users/emels/Yandex.Disk.localized/Python/PyTrading/AlorPy/Tests/05 - Dev_TSalor_long_market orders.py", line 174, in <module>
    quotes = apProvider.GetQuotes(f'{exchange}:{symbol}')[0]  # Последнюю котировку получаем через запрос

  File "/Users/emels/Yandex.Disk.localized/Python/PyTrading/AlorPy/AlorPy.py", line 396, in GetQuotes
    return self.CheckResult(requests.get(url=f'{self.apiServer}/md/v2/Securities/{symbols}/quotes', headers=self.GetHeaders()))

  File "/Users/emels/YD/Python/Alor_pilot/venv/lib/python3.10/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)

  File "/Users/emels/YD/Python/Alor_pilot/venv/lib/python3.10/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)

  File "/Users/emels/YD/Python/Alor_pilot/venv/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)

  File "/Users/emels/YD/Python/Alor_pilot/venv/lib/python3.10/site-packages/requests/sessions.py", line 687, in send
    r.content

  File "/Users/emels/YD/Python/Alor_pilot/venv/lib/python3.10/site-packages/requests/models.py", line 838, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''

  File "/Users/emels/YD/Python/Alor_pilot/venv/lib/python3.10/site-packages/requests/models.py", line 763, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

Process finished with exit code 1

**Comment by cia76** [comment]
Добрый день!

Извиняюсь за долгий ответ, только вернулся из разъездов.

По ошибке. Если она возникает не сразу, а через некоторое время, то есть подозрение как на качество канала, так и на действия брокера (например, он перезапустил сервис во время запроса). Ошибка Connection broken возникаем именно при потере связи.

Я днями оставлял соединение открытым, все работало. Что могу порекомендовать. Подержите связь несколько дней. Если появятся ошибки, пособирайте их. Я свяжусь с Алором, мы подумаем, как сделать так, чтобы даже при возникновении нештатных ситуаций библиотека работала.

**Comment by emelkas** [comment]
Еще с одной ошибкой сегодня с утра столкнулся при запуске скрипта. Так и не понял почему она возникла, т.к. через какое-то время скрипт все же запустился. Тут отсылки на мой код, но, возможно, все же получится понять причину проблемы:

2022-07-06 10:13:41.426 | INFO     | __main__:<module>:180 - Ожидаем цену 0.0185 для входа в стартовую позицию, текущая цена 0.01889
Response Web Error: 400 b'{"code":"CommandResponseTimeout","message":"Command Timeout"}' <PreparedRequest [POST]>
Traceback (most recent call last):
  File "C:\Users\s.emelyanov\PycharmProjects\Alor\AlorPy\TradeSystems\02 - VTB_long_1.py", line 187, in <module>
    send_limit_order_and_check_execution(portfolio, exchange, symbol, lots, limit_price)    # Отправляем заявку брокеру
  File "C:\Users\s.emelyanov\PycharmProjects\Alor\AlorPy\TradeSystems\02 - VTB_long_1.py", line 70, in send_limit_order_and_check_execution
    order_id = response['orderNumber']  # Номер заявки
TypeError: 'NoneType' object is not subscriptable

Process finished with exit code 1

**Comment by emelkas** [comment]
Продолжение...
Тот же скрипт проработал с 10:15, а в 13:25 выдал ошибку.

Traceback (most recent call last):
  File "C:\Users\s.emelyanov\PycharmProjects\Alor\venv\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\s.emelyanov\PycharmProjects\Alor\venv\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\s.emelyanov\PycharmProjects\Alor\venv\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\s.emelyanov\PycharmProjects\Alor\venv\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\s.emelyanov\PycharmProjects\Alor\venv\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\s.emelyanov\PycharmProjects\Alor\venv\lib\site-packages\urllib3\connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "C:\Users\s.emelyanov\PycharmProjects\Alor\venv\lib\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "C:\Users\s.emelyanov\PycharmProjects\Alor\venv\lib\site-packages\urllib3\connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x0000012E78DCD570>, 'Connection to oauth.alor.ru timed out. (connect timeout=None)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\s.emelyanov\PycharmProjects\Alor\venv\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Users\s.emelyanov\PycharmProjects\Alor\venv\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Users\s.emelyanov\PycharmProjects\Alor\venv\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='oauth.alor.ru', port=443): Max retries exceeded with url: /refresh?token=dc73285a-4fe7-40ad-be8c-ccac3bc44b0c (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000012E78DCD570>, 'Connection to oauth.alor.ru timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\s.emelyanov\PycharmProjects\Alor\AlorPy\TradeSystems\02 - VTB_long_1.py", line 187, in <module>
    send_limit_order_and_check_execution(portfolio, exchange, symbol, lots, limit_price)    # Отправляем заявку брокеру
  File "C:\Users\s.emelyanov\PycharmProjects\Alor\AlorPy\TradeSystems\02 - VTB_long_1.py", line 83, in send_limit_order_and_check_execution
    order_status = apProvider.GetOrder(portfolio, exchange, order_id)['status']
  File "C:\Users\s.emelyanov\PycharmProjects\Alor\AlorPy\AlorPy.py", line 266, in GetOrder
    return self.CheckResult(requests.get(url=f'{self.apiServer}/md/v2/clients/{exchange}/{portfolio}/orders/{orderId}', headers=self.GetHeaders()))
  File "C:\Users\s.emelyanov\PycharmProjects\Alor\AlorPy\AlorPy.py", line 64, in GetHeaders
    return {'Content-Type': 'application/json', 'Authorization': f'Bearer {self.GetJWTToken()}'}
  File "C:\Users\s.emelyanov\PycharmProjects\Alor\AlorPy\AlorPy.py", line 41, in GetJWTToken
    response = requests.post(url=f'{self.oauthServer}/refresh', params={'token': self.refreshToken})  # Запрашиваем новый JWT токен с сервера аутентификации
  File "C:\Users\s.emelyanov\PycharmProjects\Alor\venv\lib\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\s.emelyanov\PycharmProjects\Alor\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\s.emelyanov\PycharmProjects\Alor\venv\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\s.emelyanov\PycharmProjects\Alor\venv\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\s.emelyanov\PycharmProjects\Alor\venv\lib\site-packages\requests\adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='oauth.alor.ru', port=443): Max retries exceeded with url: /refresh?token=dc73285a-4fe7-40ad-be8c-ccac3bc44b0c (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000012E78DCD570>, 'Connection to oauth.alor.ru timed out. (connect timeout=None)'))

Process finished with exit code 1

**Comment by cia76** [comment]
Добрый день!

Алор перезагружает сервер перед торговой сессией каждый день. Поэтому, держать постоянное соединение не получится. Здесь вы правы.

Как решается эта задача. В торговую систему вводится расписание торгов по времени. Подписываемся на приход нового бара, ТС работает в этом обработчике. Перед тем, как что-то запросить с сервера или подать заявку, система сверяется с расписанием. Если это торговое время, то запрос отправляет.

При торговле есть множество нюансов, все они отображены в полученных ошибках:

1. ERROR: (853) Only orders with Close Auction Price are available. Close Auction Price is 0.018785. Перед отправкой заявки, проверяйте время. Если сейчас идет клиринг, то не отправляйте заявку. Дождитесь окончания клиринга, тогда отправляйте.

2.  Response Web Error: 400 b'{"code":"CommandResponseTimeout","message":"Command Timeout"} Это таймаут у Алора. Возможно, в это время Алор перегружает сервер. Здесь можно отловить ошибку через try. Аналогично и с ошибкой TimeoutError: [WinError 10060]

Если считать, что Алор в любой момент может перегрузить сервер, то нужно все взаимодействия с ним делать через try, отлавливать ошибки и реагировать на них. В некоторых случаях ждать, в некоторых устанавливать соединение заново.

По работе с расписанием [разбирал код у себя в блоге здесь](https://finlab.vip/marketnonworkinghours/).

**Comment by emelkas** [comment]
Учитывая что я сталкивался с ошибками во время торговой сессии, вариант с расписанием решит проблему не в полной мере. Так же, расписание периодически меняется, да и остается вопрос с неторговыми днями. Их надо в скрипт забивать по сути вручную, что мне делать бы не хотелось.
В общем, я для себя решил вопрос через использование try (скрипт работает без остановок с утра пятницы, отработал в выходные и в понедельник). Расписание, думаю, все равно имеет смысл прикрутить: займусь на досуге. 
Игорь, большое спасибо, за уделенное внимание моему вопросу и подробные рекомендации.
