### ISSUE TITLE
Не запускаются скрипты из example

### ISSUE THREAD

**Issue by Selasii** [cia76/AlorPy#14]
Не запускается ни один из примерочных скриптов. Текст ошибки:
```
(venv) D:\alorTrading>
python Bars.py
Traceback (most recent call last):
  File "D:\alorTrading\Bars.py", line 8, in <module>
    from AlorPy import AlorPy  # Работа с Alor OpenAPI V2
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\alorTrading\AlorPy\__init__.py", line 1, in <module>
    from .AlorPy import AlorPy
  File "D:\alorTrading\AlorPy\AlorPy.py", line 14, in <module>
    from jwt import decode
ImportError: cannot import name 'decode' from 'jwt' (D:\alorTrading\venv\Lib\site-packages\jwt\__init__.py)
```

Установленные пакеты:
```
(venv) D:\alorTrading>pip list
Package            Version
------------------ -----------
certifi            2024.2.2
cffi               1.16.0
charset-normalizer 3.3.2
cryptography       42.0.7
idna               3.7
jwt                1.3.1
numpy              1.26.4
pandas             2.2.2
pip                24.0
pycparser          2.22
python-dateutil    2.9.0.post0
pytz               2024.1
requests           2.32.1
six                1.16.0
tzdata             2024.1
urllib3            2.2.1
websockets         12.0
```

**Comment by cia76** [comment]
Добрый день!

У Вас установлена старая версия библиотеки [PyJWT](https://pyjwt.readthedocs.io/en/stable/). Работать будет версия 2.8.0 и выше.

**Comment by Selasii** [comment]
Спасибо, помогло!
