### ISSUE TITLE
Проблема с несколькими подписками.

### ISSUE THREAD

**Issue by fingoldo** [cia76/AlorPy#9]
Здравствуйте, спасибо за библиотеку, а поддерживается ли вообще получение стримов на один обработчик по нескольким инструментам сразу?
При попытке сделать

```

    for row in tqdmu(res.head(10).itertuples(), leave=False):
        guid = ap_provider.order_book_get_and_subscribe(row.exchange, row.symbol)  # Получаем код подписки
```

получаю

> 1it [00:01,  1.78s/it]Exception in thread Thread-4:
> Traceback (most recent call last):
>   File "C:\ProgramData\Anaconda3\lib\threading.py", line 980, in _bootstrap_inner
>     self.run()
>   File "C:\ProgramData\Anaconda3\lib\threading.py", line 917, in run
>     self._target(*self._args, **self._kwargs)
>   File "C:\ProgramData\Anaconda3\lib\asyncio\runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
>     return future.result()
>   File "D:\Upd\Programming\PythonCodeRepository\AlorPy\AlorPy.py", line 1020, in subscribe_async
>     await self.web_socket.send(dumps(request))  # Отправляем запрос
> AttributeError: 'NoneType' object has no attribute 'send'
> 2it [00:02,  1.07s/it]2023-06-19 09:19:16,869 - ERROR - default_exception_handler-line:1753 - Fatal error on SSL transport
> protocol: <asyncio.sslproto.SSLProtocol object at 0x000001E6380C8190>
> transport: <_ProactorSocketTransport fd=2456 read=<_OverlappedFuture pending overlapped=<pending, 0x1e637db3ee0> cb=[_ProactorReadPipeTransport._loop_reading()]> write=<_OverlappedFuture finished result=213> write_bufsize=213>
> Traceback (most recent call last):
>   File "C:\ProgramData\Anaconda3\lib\asyncio\sslproto.py", line 678, in _process_write_backlog
>     data, offset = self._write_backlog[0]
> IndexError: deque index out of range
> 2023-06-19 09:19:18,088 - ERROR - transfer_data-line:1015 - data transfer failed
> Traceback (most recent call last):
>   File "C:\ProgramData\Anaconda3\lib\site-packages\websockets\legacy\protocol.py", line 959, in transfer_data
>     message = await self.read_message()
>   File "C:\ProgramData\Anaconda3\lib\site-packages\websockets\legacy\protocol.py", line 1029, in read_message
>     frame = await self.read_data_frame(max_size=self.max_size)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\websockets\legacy\protocol.py", line 1104, in read_data_frame
>     frame = await self.read_frame(max_size)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\websockets\legacy\protocol.py", line 1161, in read_frame
>     frame = await Frame.read(
>   File "C:\ProgramData\Anaconda3\lib\site-packages\websockets\legacy\framing.py", line 68, in read
>     data = await reader(2)
>   File "C:\ProgramData\Anaconda3\lib\asyncio\streams.py", line 723, in readexactly
>     await self._wait_for_data('readexactly')
>   File "C:\ProgramData\Anaconda3\lib\asyncio\streams.py", line 517, in _wait_for_data
>     await self._waiter
>   File "C:\ProgramData\Anaconda3\lib\asyncio\sslproto.py", line 678, in _process_write_backlog
>     data, offset = self._write_backlog[0]
> IndexError: deque index out of range

**Comment by fingoldo** [comment]
Оказывается, проблема была с моей стороны в неправильной инициализации AlorPy.
Теперь данные в обработчик приходят, но только один раз с каждой подписки, даже если я запускаю всего одну (.

**Comment by cia76** [comment]
Для таких случаев есть примеры. Начните с запуска 01 - Connect.py  и 05 - Stream.py
